url: http://agency.networqi.com

# Site settings
title: networQi agency
email: contact@networqi.com
description: Sites web haut de gamme à partir de 349€ pour THÉRAPEUTES & PRATICIENS

# Team names, titles and social links
people:
- name: Anne-Laure Paccoud
  pic: anne-laure
  position: Chef de projet
  social:
    - title: linkedin
      url: https://fr.linkedin.com/in/alpaccoud
    - title: facebook
      url: https://www.facebook.com/networqi
    - title: twitter
      url: https://twitter.com/networqi

- name: Arnaud Dezandee
  pic: arnaud-dezandee
  position: Ingénieur Dévelopement
  social:
    - title: linkedin
      url: https://fr.linkedin.com/in/adezandee
    - title: github
      url: https://github.com/Adezandee

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/networqi
  - title: facebook
    url: https://www.facebook.com/networqi
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/NetworQi/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
